name: Test (lint and typehints)

on:
  push:
    branches:
      - main
      - workflow_update
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install ruff mypy

    - name: Run ruff
      run: |
        ruff check $(git-ls '*.py')

    - name: Run mypy
      run: |
        mypy main.py
